export const c = {
  cream: "#FAF7F0",
  card: "#FFFDF7",
  sand: "#F1ECDD",
  line: "#DCD3BE",
  gold: "#B79A5D",
  goldSoft: "#E7DCBE",
  ink: "#2B3B2A",
  green: "#3F5A3C",
  sage: "#5B6753",
  sageLight: "#7C8F5D",
  mint: "#CFE6D4",
  olive: "#8A7F4A",
  white: "#FFFDF7",
  paleText: "#F1ECDD",
} as const;
